### ISSUE TITLE
Adding rustfmt.toml

### ISSUE THREAD

**Issue by emirror-de** [headless-studio/leptos-leaflet#11]
To get the same code formatting for every developer, would you be interested in adding a `rustfmt.toml` to this project?

For example:
```toml
max_width = 80
format_strings = false
imports_layout = "HorizontalVertical"
imports_granularity="One"
reorder_imports = true
```
